"""Increase phone_number length

Revision ID: 65385b356e9f
Revises: b7d78d2e99f1
Create Date: 2024-09-01 12:50:49.730342

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65385b356e9f'
down_revision = 'b7d78d2e99f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###
